-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbWVe5KQKOPaqwfq1
NLQ1YfMrnddjjy8AEdz3eqspMbmgCgYIKoZIzj0DAQehRANCAARgIqPntBHp0pwW
miGuqWQPcp2gioMGMhOjGG457AxpcggsaM9TcYHJwy7IV76UR6VVTgCT42tkZEVh
iSW5M0Ou
-----END PRIVATE KEY-----