// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZIml1fb_NTvOf29rO7E0v9VFC412mKc',
    appId: '1:507056902272:web:5a13c49ca5d2eb8a355665',
    messagingSenderId: '507056902272',
    projectId: 'jeriasmath',
    authDomain: 'jeriasmath.firebaseapp.com',
    storageBucket: 'jeriasmath.appspot.com',
    measurementId: 'G-PCJBC5X14C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUtnwRpF3KSEwvefKkGWsZ7MlwaHUkS4',
    appId: '1:507056902272:android:60fbf209365aa517355665',
    messagingSenderId: '507056902272',
    projectId: 'jeriasmath',
    storageBucket: 'jeriasmath.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAeNltd9X9ap322HCBVDBpACbfVkfsPbU',
    appId: '1:507056902272:ios:dd1a64151eb4ce43355665',
    messagingSenderId: '507056902272',
    projectId: 'jeriasmath',
    storageBucket: 'jeriasmath.appspot.com',
    iosClientId: '507056902272-c172hj86ivltir8omr5lss0gq8hs9oq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeriasMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAeNltd9X9ap322HCBVDBpACbfVkfsPbU',
    appId: '1:507056902272:ios:e302b32240105838355665',
    messagingSenderId: '507056902272',
    projectId: 'jeriasmath',
    storageBucket: 'jeriasmath.appspot.com',
    iosClientId: '507056902272-uua8qaahug2l2lgh2a07b4r919o190ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeriasMath.RunnerTests',
  );
}
